### ISSUE TITLE
Onboarding key not found

### ISSUE THREAD

**Issue by johnnybegood88** [NebraLtd/helium-miner-software#109]
Hey,

Finally have received some of our Nebra miners, but one of them shows the issue "Onboarding key not found". Does anyone know how to resolve this issue? 

Cheers.

**Comment by KevinWassermann94** [comment]
Please send us a mail to sales@nebra.com with your mac address, the variant(indoor/ outdoor) and your frequency.

**Comment by shawaj** [comment]
Do you have a ticket number?

**Comment by johnnybegood88** [comment]
#261589 Kevin has replied once asking for specifications, but not anymore thereafter.

**Comment by shawaj** [comment]
@KevinWassermann94 FYI

@johnnybegood88 it takes a bit of time to get it fixed

**Comment by Roomer562** [comment]
Hello guys, have exactly same problem, ticket has been submitted a week ago, ticket #260727, can you please fix it?  Its frustrating to have this wonderful device dead on the table (its connected, in case you need that device to be online to apply fix). Cheers everyone! @shawaj @KevinWassermann94

**Comment by shawaj** [comment]
yes it needs to be left online @Roomer562

**Comment by johnnybegood88** [comment]
@shawaj would have been great to mention that from the start, cause ours is not online. 😫😫😫

**Comment by jgalang81** [comment]
Getting the same error message ever since I got my miner 

Ticket (#262791) 

1) Model is for indoors
2) See attached screenshot the diagnostic test for Mac address, wired connection F0:4C:D5:03:C2:7D
3) Frequency US915
4) Will be using the unit in Canada only
5) Unit powered though the power socket, using the power adapter in the package.

Got a response back from Salman Faris here and that he will look into my ticket, no response yet.

Yes it would definitely be nice to have some form of announcement in regards to the onboarding issues, expectations are real high, this way when people get them they are not kept out of dark of information.

![2021-08-14 09_56_23-Window](https://user-images.githubusercontent.com/88591497/129448631-8010ca42-8de4-4dc1-be7d-9d4122c5fff8.png)

**Comment by devicefckdup** [comment]
Hello there...

I was wondering if you could perform factory resets on two of my NEBRA indoor hotspots? I cant do it myself since I am unable to approach your official NEBRA dashboard...the bug in question is "the device does not exist". Ive tryed a dozen times, scanned the codes over and over again, manually entered codes...but none of my hotspots is recognized by your dashboard software. I ve already submitted a ticket to nebra support email, but no answer has been given. Both of my hotspots suddenly stopped all activity, without any logical reason...and they are dead for weeks now. They previously worked fine, my internet connection is top of the line, ports are open, the devices are backed up with colling units, everything should be in order...except it isnt, and my units arent mining at all. I ve manually unplugged and plugged them numerous time...it didnt helped, restarted the routers...didnt helped. Ergo...I am here, asking you for your help and guidance.
I can provide you with additional information...MAC codes, ETH code and all that, just tell me where to approach you...since nebra support email doesnt give me any feedback for weeks now.

**Comment by jgalang81** [comment]
> @KevinWassermann94 FYI
> 
> @johnnybegood88 it takes a bit of time to get it fixed

How long for these issues to be fixed? Is it a week or two, a month, 6 months a year? Give us some updates please.

**Comment by shawaj** [comment]
Closing this issue as it's not the right place for support of this kind.

This is the way to get help with these issues:
> Please send us a mail to [sales@nebra.com](mailto:sales@nebra.com) with your mac address, the variant(indoor/ outdoor) and your frequency.

**Comment by jgalang81** [comment]
#response_container_BBPPID{font-family: initial; font-size:initial; color: initial;} Hi Aaron,I've already sent an email to ***@***.*** and I have getting intermittent and zero replies from your support team. If support was prompt in regards to this kind of issues. We wouldn't be frustrated or feel like getting abandoned from a customer experience.                                                                                                                                             Sent via BlackBerry Hub+ Inbox for Android                                                                                                                                                                           From: ***@***.***: August 18, 2021 11:40 a.m.To: ***@***.*** to: ***@***.***: ***@***.***; ***@***.***: Re: [NebraLtd/helium-miner-software] Onboarding key not found (#109)  
Closing this issue as it's not the right place for support of this kind.
This is the way to get help with these issues:

Please send us a mail to ***@***.*** with your mac address, the variant(indoor/ outdoor) and your frequency.

**Comment by shawaj** [comment]
https://github.com/NebraLtd/helium-miner-software/issues/109#issuecomment-901219861
