### ISSUE TITLE
Release 2021.11.10.0 

### ISSUE THREAD

**Issue by marvinmarnold** [NebraLtd/helium-miner-software#203]
https://engineering.helium.com/2021/11/10/blockchain-release-poc-v11-preparations.html

**Comment by marianpilka** [comment]
So when are you going to have it ready?

**Comment by shawaj** [comment]
https://github.com/NebraLtd/hm-miner/commit/6ee720d968173f50c92a67f538bc69837dd61b9f

**Comment by marvinmarnold** [comment]
@KevinWassermann94 @shawaj @vpetersson I think this can be closed because of: https://github.com/NebraLtd/helium-miner-software/issues/210 and the fact that 2021.11.10.0 is not performing well in testnet. Thoughts?

**Comment by shawaj** [comment]
@marvinmarnold I agree. No point merging #210 or #195 now really.

But we should aim to release this within the next 24 hours so that we don't they don't get too far behind. And if there's any significant issues with it we should of course report to Helium.

We can't get too far behind releases or it can cause issues. Bit of a catch 22... Especially in periods like this where there has been 6 x GA updates in 2 weeks!

One other thing in thinking is that we need two testnets:
1. Production testnet. Mirrors production apart from miner bumps (or perhaps other single-container bumps)
2. A more beta testnet where we test more elaborate changes

Problem with how we have it now is that we aren't testing on units that are running same containers as production so the testing is not a perfect representation of what we are trying to test.

**Comment by KevinWassermann94** [comment]
@KevinWassermann94 @shawaj @vpetersson Yes I agree. This can be closed in favor of #210 
We should really aim to get that one out as soon as possible after we can confirm the hotspots are performing well. This release includes important fixes that should fix hotspots not witnessing/ beaconing and is important to get out now

2021.11.10.0 the issues with hotspots showing offline seems like it was a temporary issue. The affected units have been back online and witnessing

**Comment by vpetersson** [comment]
Closed in favor of 210

**Comment by shawaj** [comment]
> We should really aim to get that one out as soon as possible after we can confirm the hotspots are performing well. 

Agreed
