### ISSUE TITLE
Zero beaconing since firmware 2021.12.14.0

### ISSUE THREAD

**Issue by anders462** [NebraLtd/helium-miner-software#312]
- [X] I understand that this is only to report software bugs and **not** for customer support. Please use [nebra.io/helium-support](https://nebra.io/helium-support).

**Describe the bug**
Many Nebra hotspot owners have not seen any beacons sent out since the update to 2021.12.14.0 this week. I have 3 Nebra hotspots and non send any beacons anymore. My freedom hotspot works fine and also other hotspots nearby the 3 Nebra's by other Makers beacons regularly. 

**To Reproduce**
1. Go to https://explorer.helium.com/hotspots/112wWWe19aw9aT4tdh81gqMw2GsPo9ZLytNVMDBDG9C2EcqjBpQq
2. Click on Activity and Beacons
3. Scroll down and see the absence of beacons.
4. Look at neighboring hotspots and see that they are beaconing.

**Expected behavior**
I expect that my Nebra hotspot beacon 1-3 times a day at least, not be missing for many days

**Screenshots**
N/A

**Desktop (please complete the following information):**
N/A

**Smartphone (please complete the following information):**
N/A

**Additional context**
N/A

**Comment by badaczewski** [comment]
Wow, I was reviewing my hotspot and I haven't sent a beacon since 13 Dec 2021, 6:29am.

Explorer:
https://explorer.helium.com/hotspots/11vFoCH9qye2qz3yy8rR9DGbtrybsxMVWC5DvWyfkh5YoYLngm7/activity

Reference from Nebra Guide:
"You will beacon, on average, 3 times a day. If there are multiple hotspots around you, you can sometimes see your hotspot exceed 60 witnesses per day. Several variables affect your potential rewards. Helium releases software updates that are required to be implemented by all vendors."

Link:
https://helium.nebra.com/handy-guides/first-days

**Comment by Cootmo** [comment]
Same issue. No beacons since the last update. Not seeing any activity with the green light (indoor model) and Bluetooth module does not activate on power up. Somehow still able to witness and challenge.

**Comment by vpetersson** [comment]
This is not a support forum. Please contact [support@nebra.com](mailto:support@nebra.com).
